"""
Regression tests for google_api.py's _fetch_refresh_token_from_redis()
(Phase 8, Milestone 8.8) -- the Python pipeline's read of the same live,
Redis-backed credential store dashboard/api/_lib/credentialStore.js writes
to. No real Upstash account or real Google credentials anywhere in this
file: urllib.request.urlopen is monkeypatched to return a fixed response.

The interop fixture below (ciphertext/iv/authTag) was generated by a REAL
Node invocation of the exact algorithm credentialStore.js uses (AES-256-GCM,
key = SHA-256 of the encryption key string) -- not just Python encrypting
and decrypting its own data -- so this genuinely proves the two
implementations are byte-compatible, not merely self-consistent.

Run directly: python tests/test_google_api_redis_token.py
"""
import json
import os
import sys
import unittest
from unittest.mock import patch, MagicMock

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import google_api as ga  # noqa: E402

# Generated via:
#   node -e "const {createCipheriv,randomBytes,createHash}=require('crypto');
#             const key=createHash('sha256').update('interop-test-key-fixture-do-not-use-in-prod').digest();
#             const iv=randomBytes(12); const cipher=createCipheriv('aes-256-gcm',key,iv);
#             const ct=Buffer.concat([cipher.update('fixture-refresh-token-abc123','utf8'),cipher.final()]);
#             console.log(JSON.stringify({ciphertext:ct.toString('base64'),iv:iv.toString('base64'),authTag:cipher.getAuthTag().toString('base64')}))"
FIXTURE_ENCRYPTION_KEY = "interop-test-key-fixture-do-not-use-in-prod"
FIXTURE_PLAINTEXT = "fixture-refresh-token-abc123"
FIXTURE_CIPHERTEXT_B64 = "RqwOpmppwpAtGkLed9wgALPefJFHu6jyCtIXQA=="
FIXTURE_IV_B64 = "eqfTxsZvl8rT5uZ3"
FIXTURE_AUTH_TAG_B64 = "2Auu84ic+uiFeOgyP4MxDQ=="


def fake_upstash_response(record_dict):
    """Builds a fake urlopen() context manager returning Upstash's own
    { "result": "<json-string-or-null>" } response shape."""
    payload = json.dumps({"result": json.dumps(record_dict) if record_dict is not None else None}).encode()
    mock_resp = MagicMock()
    mock_resp.read.return_value = payload
    mock_resp.__enter__.return_value = mock_resp
    mock_resp.__exit__.return_value = False
    return mock_resp


class TestGoogleApiRedisToken(unittest.TestCase):
    def setUp(self):
        self._env_backup = dict(os.environ)

    def tearDown(self):
        os.environ.clear()
        os.environ.update(self._env_backup)

    def _configure_redis_env(self):
        os.environ["UPSTASH_REDIS_REST_URL"] = "https://fake-upstash.example.com"
        os.environ["UPSTASH_REDIS_REST_TOKEN"] = "fake-rest-token"
        os.environ["CREDENTIAL_ENCRYPTION_KEY"] = FIXTURE_ENCRYPTION_KEY

    def test_missing_config_returns_none_without_network_call(self):
        for var in ("UPSTASH_REDIS_REST_URL", "UPSTASH_REDIS_REST_TOKEN", "CREDENTIAL_ENCRYPTION_KEY"):
            os.environ.pop(var, None)
        with patch("urllib.request.urlopen") as mock_urlopen:
            result = ga._fetch_refresh_token_from_redis()
            self.assertIsNone(result, "missing config must return None")
            mock_urlopen.assert_not_called()

    def test_no_stored_credential_returns_none(self):
        self._configure_redis_env()
        with patch("urllib.request.urlopen", return_value=fake_upstash_response(None)):
            result = ga._fetch_refresh_token_from_redis()
            self.assertIsNone(result, "an empty Redis result (nothing connected yet) must return None, not raise")

    def test_decrypts_a_real_node_generated_ciphertext(self):
        """The critical interop assertion: this ciphertext was produced by a
        real Node crypto.createCipheriv('aes-256-gcm', ...) call using
        credentialStore.js's exact key-derivation and field layout -- if
        this passes, the two languages are genuinely byte-compatible, not
        just internally consistent with themselves."""
        self._configure_redis_env()
        record = {
            "refreshTokenCiphertext": FIXTURE_CIPHERTEXT_B64,
            "refreshTokenIv": FIXTURE_IV_B64,
            "refreshTokenAuthTag": FIXTURE_AUTH_TAG_B64,
            "connectedAccountName": "Los Tres Amigos",
            "health": "connected",
        }
        with patch("urllib.request.urlopen", return_value=fake_upstash_response(record)):
            result = ga._fetch_refresh_token_from_redis()
            self.assertEqual(result, FIXTURE_PLAINTEXT, "must decrypt to the exact plaintext Node encrypted")

    def test_wrong_encryption_key_falls_back_to_none_not_crash(self):
        self._configure_redis_env()
        os.environ["CREDENTIAL_ENCRYPTION_KEY"] = "a-completely-different-key"
        record = {
            "refreshTokenCiphertext": FIXTURE_CIPHERTEXT_B64,
            "refreshTokenIv": FIXTURE_IV_B64,
            "refreshTokenAuthTag": FIXTURE_AUTH_TAG_B64,
        }
        with patch("urllib.request.urlopen", return_value=fake_upstash_response(record)):
            result = ga._fetch_refresh_token_from_redis()
            self.assertIsNone(result, "a wrong encryption key must fail closed (None), never raise or return garbage")

    def test_network_error_falls_back_to_none_not_crash(self):
        self._configure_redis_env()
        with patch("urllib.request.urlopen", side_effect=OSError("ECONNREFUSED fake-upstash-outage")):
            result = ga._fetch_refresh_token_from_redis()
            self.assertIsNone(result, "a network error reaching Upstash must return None, never raise or crash the pipeline")

    def test_malformed_json_response_falls_back_to_none(self):
        self._configure_redis_env()
        mock_resp = MagicMock()
        mock_resp.read.return_value = b"not valid json {{{"
        mock_resp.__enter__.return_value = mock_resp
        mock_resp.__exit__.return_value = False
        with patch("urllib.request.urlopen", return_value=mock_resp):
            result = ga._fetch_refresh_token_from_redis()
            self.assertIsNone(result, "a malformed response must return None, never raise")

    def test_get_access_token_prefers_redis_over_env_var(self):
        """get_access_token() itself must try the Redis path first -- this
        drives it end-to-end (through the real token-exchange HTTP call,
        also mocked) and asserts the REDIS-sourced refresh token is the one
        actually sent to Google, not the env var fallback."""
        self._configure_redis_env()
        os.environ["GOOGLE_CLIENT_ID"] = "fake-client-id"
        os.environ["GOOGLE_CLIENT_SECRET"] = "fake-client-secret"
        os.environ["GOOGLE_REFRESH_TOKEN"] = "should-not-be-used-env-var-token"
        ga._access_token_cache["token"] = None
        ga._access_token_cache["expires_at"] = 0

        record = {
            "refreshTokenCiphertext": FIXTURE_CIPHERTEXT_B64,
            "refreshTokenIv": FIXTURE_IV_B64,
            "refreshTokenAuthTag": FIXTURE_AUTH_TAG_B64,
        }
        redis_response = fake_upstash_response(record)

        token_exchange_response = MagicMock()
        token_exchange_response.read.return_value = json.dumps({"access_token": "fresh-access-token", "expires_in": 3600}).encode()
        token_exchange_response.__enter__.return_value = token_exchange_response
        token_exchange_response.__exit__.return_value = False

        captured_request_bodies = []

        def fake_urlopen(req, timeout=None):
            if "upstash" in req.full_url:
                return redis_response
            captured_request_bodies.append(req.data)
            return token_exchange_response

        with patch("urllib.request.urlopen", side_effect=fake_urlopen):
            token = ga.get_access_token()

        self.assertEqual(token, "fresh-access-token")
        self.assertEqual(len(captured_request_bodies), 1, "exactly one token-exchange request must be made")
        sent_body = captured_request_bodies[0].decode()
        self.assertIn(f"refresh_token={FIXTURE_PLAINTEXT}", sent_body, "the Redis-sourced token must be the one sent to Google")
        self.assertNotIn("should-not-be-used-env-var-token", sent_body, "the env var fallback token must NOT be used when Redis has a value")


if __name__ == "__main__":
    unittest.main()
