// Unit tests for dashboard/api/_lib/gbpLocationAuthorization.js --
// "require approved location for Google reply" (Phase A2) plus the "prove
// LTA link-map artifact availability" final pre-deploy review item (6):
// this file specifically exercises the REAL file-missing fail-closed path
// (no test-only override installed), proving isApprovedGoogleLocationForTenant()
// denies by construction when the `_internal/gbp-location-link-map.json`
// artifact genuinely does not exist on disk -- not merely when a test
// simulates an empty map via _setGbpLocationLinkMapForTests().
//
// Run directly: node tests/test_gbp_location_authorization.js

import {
  parseGoogleReviewResourceName, isApprovedGoogleLocationForTenant,
  _setGbpLocationLinkMapForTests, _resetGbpLocationLinkMapForTests,
} from '../dashboard/api/_lib/gbpLocationAuthorization.js'
import {
  upsertTenantConfig, recordLocationApproval,
  _setRedisClientForTests as setConfigRedis, _resetRedisClientForTests as resetConfigRedis,
} from '../dashboard/api/_lib/tenantConfigStore.js'
import { DEFAULT_TENANT_ID } from '../dashboard/api/_lib/tenants.js'

function assert(cond, msg) {
  if (!cond) throw new Error(msg)
}

const results = []
async function run(name, fn) {
  try {
    await fn()
    console.log(`PASS: ${name}`)
    results.push(true)
  } catch (e) {
    console.log(`FAIL: ${name} -- ${e.message}`)
    results.push(false)
  } finally {
    _resetGbpLocationLinkMapForTests()
    resetConfigRedis()
  }
}

function fakeConfigRedis() {
  const store = {}
  return {
    hget: async (key, field) => store[key]?.[field] ?? null,
    hgetall: async (key) => ({ ...(store[key] ?? {}) }),
    hset: async (key, fields) => { store[key] = { ...(store[key] ?? {}), ...fields } },
    hdel: async (key, field) => { if (store[key]) delete store[key][field] },
    eval: async (_script, keys, args) => {
      const key = keys[0]
      const [field, expectedVersionStr, nextJson] = args
      const raw = store[key]?.[field] ?? null
      let currentVersion = '0'
      if (raw) {
        try { const decoded = JSON.parse(raw); if (decoded && decoded.configVersion !== undefined) currentVersion = String(decoded.configVersion) } catch { /* treat as version 0 */ }
      }
      if (currentVersion !== expectedVersionStr) return raw ?? false
      store[key] = { ...(store[key] ?? {}), [field]: nextJson }
      return true
    },
  }
}

// --- parseGoogleReviewResourceName -------------------------------------------

function testParsesAWellFormedReviewResourceName() {
  const parsed = parseGoogleReviewResourceName('accounts/123/locations/456/reviews/789')
  assert(parsed && parsed.locationResource === 'accounts/123/locations/456', `expected the location prefix extracted, got ${JSON.stringify(parsed)}`)
}

function testRejectsMalformedResourceNames() {
  const bad = [
    'not-a-real-resource', 'accounts/123/locations/456', 'accounts//locations/456/reviews/789',
    '../../etc/passwd', 'accounts/123/locations/456/reviews/789/extra', 123, null, undefined, '',
  ]
  for (const input of bad) {
    assert(parseGoogleReviewResourceName(input) === null, `expected null for malformed input ${JSON.stringify(input)}`)
  }
}

// --- BOOTSTRAP (LTA) path -- "prove LTA link-map artifact availability" ----

async function testBootstrapFailsClosedWhenArtifactGenuinelyMissing() {
  // Deliberately NO _setGbpLocationLinkMapForTests() override -- this
  // exercises the REAL readPrivateDataFile() call against this test
  // environment's filesystem, where dashboard/private-data/ does not
  // exist at all (it is generated by the export pipeline at deploy time,
  // never checked into the repo). loadBootstrapLinkMap() must catch that
  // and fail closed (authorize nothing), never throw and never default to
  // "authorized."
  const approved = await isApprovedGoogleLocationForTenant(DEFAULT_TENANT_ID, 'accounts/1/locations/2')
  assert(approved === false, 'a genuinely missing linked-location artifact must fail closed (deny), not throw or default to allow')
}

async function testBootstrapApprovesAnExplicitlyLinkedLocation() {
  _setGbpLocationLinkMapForTests({ 'accounts/1/locations/2': 2 })
  const approved = await isApprovedGoogleLocationForTenant(DEFAULT_TENANT_ID, 'accounts/1/locations/2')
  assert(approved === true, 'a location explicitly present in the link map must be approved')
}

async function testBootstrapDeniesAnUnlinkedLocation() {
  _setGbpLocationLinkMapForTests({ 'accounts/1/locations/2': 2 }) // something else is linked
  const approved = await isApprovedGoogleLocationForTenant(DEFAULT_TENANT_ID, 'accounts/9/locations/9')
  assert(approved === false, 'a location absent from the link map must be denied, even though the map itself loaded successfully')
}

// --- REDIS_ONLY (self-service) path ------------------------------------------

const TENANT_A = 't_gbp-authz-tenant-a'

async function testRedisOnlyApprovesFromLiveTenantConfig() {
  const client = fakeConfigRedis()
  setConfigRedis(() => client) // captured singleton -- see fakeConfigRedis()'s own note pattern elsewhere in this suite
  await upsertTenantConfig(TENANT_A, {}, { allowCreate: true, creationSource: 'migration' })
  await recordLocationApproval(TENANT_A, [{ googleLocationId: 'accounts/5/locations/6', title: 'X', address: '' }])
  const approved = await isApprovedGoogleLocationForTenant(TENANT_A, 'accounts/5/locations/6')
  assert(approved === true, 'a location present in the tenant\'s own live approvedLocations must be approved')
}

async function testRedisOnlyDeniesAnUnapprovedLocation() {
  const client = fakeConfigRedis()
  setConfigRedis(() => client)
  await upsertTenantConfig(TENANT_A, {}, { allowCreate: true, creationSource: 'migration' })
  await recordLocationApproval(TENANT_A, [{ googleLocationId: 'accounts/5/locations/6', title: 'X', address: '' }])
  const approved = await isApprovedGoogleLocationForTenant(TENANT_A, 'accounts/9/locations/9')
  assert(approved === false, 'a location NOT in the tenant\'s own approvedLocations must be denied, even though the tenant genuinely exists')
}

async function testRedisOnlyFailsClosedWhenTenantConfigMissing() {
  setConfigRedis(() => fakeConfigRedis())
  // No upsertTenantConfig() at all -- genuinely no record for this tenant.
  const approved = await isApprovedGoogleLocationForTenant('t_gbp-authz-tenant-nonexistent', 'accounts/5/locations/6')
  assert(approved === false, 'a nonexistent tenant_config must fail closed (deny), never throw or default to allow')
}

async function testRedisOnlyFailsClosedOnStoreOutage() {
  setConfigRedis(() => ({ hget: async () => { throw new Error('ECONNREFUSED simulated outage') } }))
  const approved = await isApprovedGoogleLocationForTenant(TENANT_A, 'accounts/5/locations/6')
  assert(approved === false, 'a tenant_config store outage must fail closed (deny), never throw uncaught or default to allow')
}

async function main() {
  await run('parseGoogleReviewResourceName: parses a well-formed review resource name', testParsesAWellFormedReviewResourceName)
  await run('parseGoogleReviewResourceName: rejects every malformed/hostile input', testRejectsMalformedResourceNames)

  await run('FINAL REVIEW item 6: BOOTSTRAP (LTA) fails closed when the link-map artifact is genuinely missing', testBootstrapFailsClosedWhenArtifactGenuinelyMissing)
  await run('BOOTSTRAP (LTA): approves an explicitly linked location', testBootstrapApprovesAnExplicitlyLinkedLocation)
  await run('BOOTSTRAP (LTA): denies an unlinked location even when the map loads successfully', testBootstrapDeniesAnUnlinkedLocation)

  await run('REDIS_ONLY: approves a location from the tenant\'s own live approvedLocations', testRedisOnlyApprovesFromLiveTenantConfig)
  await run('REDIS_ONLY: denies a location not in the tenant\'s own approvedLocations', testRedisOnlyDeniesAnUnapprovedLocation)
  await run('REDIS_ONLY: fails closed when tenant_config does not exist', testRedisOnlyFailsClosedWhenTenantConfigMissing)
  await run('REDIS_ONLY: fails closed on a tenant_config store outage', testRedisOnlyFailsClosedOnStoreOutage)

  console.log()
  if (results.every(Boolean)) {
    console.log(`ALL ${results.length} TESTS PASSED`)
    process.exit(0)
  }
  console.log(`${results.filter(r => !r).length} of ${results.length} TESTS FAILED`)
  process.exit(1)
}

main()
