// Multi-Tenant Phase 4Q.1 -- POST/GET /api/admin?action=... -- platform-
// admin-only access-code management (create/list/revoke). This is a NEW
// top-level serverless function, which the Phase 4Q design report flagged
// explicitly as blocked on Vercel Hobby's 12-function ceiling
// (tenant-entitlements/[action].js's own header documents that ceiling was
// already reached). Per the reviewed Phase 4Q decision: do NOT add this to
// tenant-entitlements/[action].js as a permanent home; this file exists as
// the dedicated route that decision called for. DO NOT PUSH/DEPLOY this
// branch until the Vercel Pro upgrade (which removes the 12-function
// ceiling) is actually in place -- see the Phase 4Q.1 implementation
// report for the exact pre-push gate this creates.
//
// AUTHORIZATION: isSuperAdmin(account) (auth.js) -- the SAME narrow gate
// tenant-ops/[action].js and tenant-entitlements/[action].js already use
// (today: only Los Tres Amigos's own Owner accounts). No new authorization
// system. The acting admin's identity is always server-derived from their
// session (requireAuth), never from request input.
//
// The raw access code is generated by accessCodeStore.js and returned
// here EXACTLY ONCE, in the create-access-code response -- never stored,
// never retrievable again, never logged (this file never logs a request
// body or response body wholesale, only structured audit fields that
// explicitly exclude the raw code).

import { requireAuth, isSuperAdmin } from '../_lib/auth.js'
import { resolveTenantId } from '../_lib/tenants.js'
import { enforceRateLimit } from '../_lib/rateLimit.js'
import { appendAuditEntry, clientIp } from '../_lib/auditLog.js'
import {
  createAccessCode, listAccessCodes, revokeAccessCode, getAccessCodeByHash,
  AccessCodeStoreUnavailableError,
} from '../_lib/accessCodeStore.js'
import { isValidPlanId } from '../_lib/plans.js'

async function requireSuperAdmin(req, res) {
  const account = await requireAuth(req, res, null)
  if (!account) return null
  if (!isSuperAdmin(account)) {
    res.status(403).json({ error: 'forbidden', message: 'You do not have permission to perform this action.' })
    return null
  }
  return account
}

// Never returns the raw code (it was never stored) -- listing is always
// safe to show in full, including redemptions[] (tenantId/userId/
// redeemedAt only, never a token/code).
async function listAccessCodesAction(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'method_not_allowed' })
  const account = await requireSuperAdmin(req, res)
  if (!account) return
  try {
    const codes = await listAccessCodes()
    return res.status(200).json({ codes })
  } catch (err) {
    if (err instanceof AccessCodeStoreUnavailableError) {
      console.error(`[admin/list-access-codes] ${err.message}`)
      return res.status(503).json({ error: 'service_unavailable', message: 'This is temporarily unavailable. Please try again shortly.' })
    }
    throw err
  }
}

// POST { prefix, plan, discountPercent?, discountFixedCents?, trialDays?,
//        paymentRequired?, expiresAt?, maxRedemptions?, allowedEmail?,
//        allowedEmailDomain?, clientLabel? }
async function createAccessCodeAction(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' })
  const account = await requireSuperAdmin(req, res)
  if (!account) return

  const allowed = await enforceRateLimit(req, res, `admin-create-access-code:${account.userId}`, { requestsPerWindow: 30, windowSeconds: 60 })
  if (!allowed) return

  const {
    prefix, plan, discountPercent = null, discountFixedCents = null, trialDays = null,
    paymentRequired = true, expiresAt = null, maxRedemptions = 1,
    allowedEmail = null, allowedEmailDomain = null, clientLabel = null,
  } = req.body ?? {}

  if (!isValidPlanId(plan)) {
    return res.status(400).json({ error: 'invalid_request', message: 'A valid plan is required.' })
  }
  if (typeof prefix !== 'string' || !/^[A-Za-z0-9-]{2,20}$/.test(prefix)) {
    return res.status(400).json({ error: 'invalid_request', message: 'Prefix must be 2-20 letters, digits, or hyphens.' })
  }
  if (discountPercent != null && discountFixedCents != null) {
    return res.status(400).json({ error: 'invalid_request', message: 'Choose either a percentage or a fixed discount, not both.' })
  }
  if (!Number.isInteger(maxRedemptions) || maxRedemptions < 1 || maxRedemptions > 100000) {
    return res.status(400).json({ error: 'invalid_request', message: 'Max redemptions must be a positive integer.' })
  }
  if (expiresAt != null && Number.isNaN(new Date(expiresAt).getTime())) {
    return res.status(400).json({ error: 'invalid_request', message: 'Expiration must be a valid date.' })
  }

  try {
    const { rawCode, record } = await createAccessCode({
      prefix: prefix.toUpperCase(), plan, discountPercent, discountFixedCents, trialDays,
      paymentRequired: Boolean(paymentRequired), expiresAt, maxRedemptions,
      allowedEmail, allowedEmailDomain, clientLabel, createdBy: account.userId,
    })

    await appendAuditEntry(resolveTenantId(account), {
      actorId: account.userId, actorEmail: account.email, ip: clientIp(req),
      action: 'access_code.created', entity: 'access_code', entityId: record.codeHash,
      result: 'success',
      message: `Created access code (plan: ${plan}, maxRedemptions: ${maxRedemptions}${clientLabel ? `, client: ${clientLabel}` : ''}).`,
    })

    // rawCode is returned to the admin's OWN response exactly once -- it
    // is never included in the audit entry above, never logged elsewhere.
    return res.status(200).json({ rawCode, code: record })
  } catch (err) {
    if (err instanceof AccessCodeStoreUnavailableError) {
      console.error(`[admin/create-access-code] ${err.message}`)
      return res.status(503).json({ error: 'service_unavailable', message: 'This is temporarily unavailable. Please try again shortly.' })
    }
    if (err instanceof TypeError) {
      return res.status(400).json({ error: 'invalid_request', message: err.message })
    }
    throw err
  }
}

// POST { codeHash }
async function revokeAccessCodeAction(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'method_not_allowed' })
  const account = await requireSuperAdmin(req, res)
  if (!account) return

  const { codeHash } = req.body ?? {}
  if (typeof codeHash !== 'string' || !codeHash) {
    return res.status(400).json({ error: 'invalid_request', message: 'codeHash is required.' })
  }

  try {
    const existing = await getAccessCodeByHash(codeHash)
    if (!existing) {
      return res.status(404).json({ error: 'not_found', message: 'No such access code.' })
    }
    const updated = await revokeAccessCode(codeHash)
    await appendAuditEntry(resolveTenantId(account), {
      actorId: account.userId, actorEmail: account.email, ip: clientIp(req),
      action: 'access_code.revoked', entity: 'access_code', entityId: codeHash,
      result: 'success', message: `Revoked access code (plan: ${existing.plan}).`,
    })
    return res.status(200).json({ code: updated })
  } catch (err) {
    if (err instanceof AccessCodeStoreUnavailableError) {
      console.error(`[admin/revoke-access-code] ${err.message}`)
      return res.status(503).json({ error: 'service_unavailable', message: 'This is temporarily unavailable. Please try again shortly.' })
    }
    throw err
  }
}

export default async function handler(req, res) {
  switch (req.query?.action) {
    case 'list-access-codes':   return listAccessCodesAction(req, res)
    case 'create-access-code':  return createAccessCodeAction(req, res)
    case 'revoke-access-code':  return revokeAccessCodeAction(req, res)
    default:                    return res.status(404).json({ error: 'not_found' })
  }
}
